ArticleManagementSystem/Models/Article.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ArticleManagementSystem.Models
{
    public class Article
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Description { get; set; }

        [Required, DataType(DataType.Date)]
        public DateTime Date { get; set; }

        [Required]
        public int CreatedBy { get; set; }
    }
}

ArticleManagementSystem/Controllers/Api/ArticlesController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using ArticleManagementSystem.Models;
using ArticleManagementSystem.Repositories;

namespace ArticleManagementSystem.Controllers.Api
{
    [ApiController]
    [Route("api/[controller]")]
    public class ArticlesController : ControllerBase
    {
        private readonly IArticleRepository articleRepository;

        public ArticlesController(IArticleRepository articleRepository)
        {
            this.articleRepository = articleRepository;
        }

        // GET: api/articles
        [HttpGet]
        public IEnumerable<Article> Get([FromQuery(Name = "startDate")] string startDate, [FromQuery(Name = "endDate")] string endDate)
        {
            List<Article> articles;

            if (DateTime.TryParse(startDate, out DateTime startDateTime) && DateTime.TryParse(endDate, out DateTime endDateTime))
            {
                articles = this.articleRepository.GetArticles(startDateTime, endDateTime);
            }
            else
            {
                articles = this.articleRepository.GetArticles();
            }

            return articles;
        }

        // GET api/articles/5
        [HttpGet("{id}")]
        public Article Get(int id)
        {
            return this.articleRepository.GetArticle(id);
        }
    }
}

ArticleManagementSystem/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Mvc;
using ArticleManagementSystem.Models;
using Microsoft.AspNetCore.Authorization;
using ArticleManagementSystem.Repositories;
using ArticleManagementSystem.Services;

namespace ArticleManagementSystem.Controllers
{
    [Authorize]
    public class ArticleController : Controller
    {
        private readonly IArticleRepository articleRepository;
        private readonly UserService userService;

        public ArticleController(IArticleRepository articleRepository, UserService userService)
        {
            this.articleRepository = articleRepository;
            this.userService = userService;
        }

        [HttpGet]
        public IActionResult Index([FromQuery(Name = "search")] string searchTerm, [FromQuery(Name = "sortTitleBy")] string sortTitleBy)
        {
            return View(this.articleRepository.GetArticles(searchTerm, this.userService.GetAuthUserID(), sortTitleBy));
        }

        [HttpGet]
        public IActionResult Create() => View();

        [HttpPost]
        public IActionResult Create([Bind("Title", "Description", "Date")] Article article)
        {
            if (ModelState.IsValid)
            {
                article.CreatedBy = this.userService.GetAuthUserID();
                this.articleRepository.Create(article);

                return RedirectToAction(nameof(Index));
            }

            return View(article);
        }

        [HttpGet]
        public IActionResult Edit(int ID)
        {
            Article article = this.articleRepository.GetArticle(ID, this.userService.GetAuthUserID());

            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        [HttpPost]
        public IActionResult Edit(int ID, [Bind("ID", "Title", "Description", "Date")] Article article)
        {
            if (ID != article.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                article.CreatedBy = this.userService.GetAuthUserID();
                this.articleRepository.Update(article);

                return RedirectToAction(nameof(Index));
            }

            return View(article);
        }

        [HttpGet]
        public IActionResult Delete(int ID)
        {
            if (this.articleRepository.GetArticle(ID, this.userService.GetAuthUserID()) == null)
            {
                return NotFound();
            }

            this.articleRepository.Delete(ID);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Show(int ID)
        {
            Article article = this.articleRepository.GetArticle(ID);

            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }
    }
}

ArticleManagementSystem/Views/Article/Create.cshtml
@model Article
@{
    ViewData["Title"] = "Create Article";
}

<h4>@ViewData["Title"]</h4>
<hr />
<div class="row">
    <div class="col-4">
        <form method="post" asp-action="Create">
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" autocomplete="off"/>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" autocomplete="off"/>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" autocomplete="off"/>
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col">
                    <button type="submit" class="btn btn-primary mb-3">Save</button>
                    <br/>
                    <a asp-action="Index">Back to List</a>
                </div>
            </div>
        </form>
    </div>
</div>

ArticleManagementSystem/Views/Article/Edit.cshtml
@model Article
@{
    ViewData["Title"] = "Edit Article";
}

<h4>@ViewData["Title"]</h4>
<hr />
<div class="row">
    <div class="col-4">
        <form method="post" asp-action="Edit" asp-route-id="@Model.ID">
            <input type="hidden" asp-for="ID"/>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" autocomplete="off"/>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" autocomplete="off"/>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" autocomplete="off"/>
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col">
                    <button type="submit" class="btn btn-primary mb-3">Update</button>
                    <br/>
                    <a asp-action="Index">Back to List</a>
                </div>
            </div>
        </form>
    </div>
</div>

ArticleManagementSystem/Views/Article/Index.cshtml
@{
    ViewData["Title"] = "Article List";
    int counter = 1;
    string sortTitleBy = Context.Request.Query["sortTitleBy"];
}

<h4>@ViewData["Title"]</h4>
<hr/>
<div class="row mb-3">
    <div class="col-4">
        <a asp-action="Create" class="btn btn-primary">Create new article</a>
    </div>

    <!-- Filtering & Sorting -->
    <div class="col text-right">
        <form method="get" asp-controller="Article" asp-action="Index">
            <div class="row justify-content-end">
                <div class="col">
                    <label class="control-label mr-2">Sort Name By: </label>
                    <select class="form-control d-inline-block w-25" name="sortTitleBy">
                        <!option value="asc" @( sortTitleBy == "asc" ? "selected" : "" )>ASC</!option>
                        <!option value="desc" @( sortTitleBy == "desc" ? "selected" : "" )>DESC</!option>
                    </select>
                </div>
                <div class="col-4">
                    <input type="text" class="form-control" name="search" placeholder="Search" autocomplete="off"/>
                </div>
                <div class="col-auto">
                    <button type="submit" class="btn btn-primary">Filter</button>
                </div>
            </div>
        </form>
    </div>
</div>

<!-- Article List -->
<div class="row">
    <div class="col">
        <table class="table table-bordered table-striped" id="article-table">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Date</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count > 0)
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="number-order">@counter</td>
                            <td>@item.Title</td>
                            <td>@item.Description</td>
                            <td>@item.Date.ToShortDateString()</td>
                            <td class="action">
                                <a asp-action="Show" asp-route-id="@item.ID" class="btn btn-sm btn-success details">Details</a>
                                <a asp-action="Edit" asp-route-id="@item.ID" class="btn btn-sm btn-primary edit">Edit</a>
                                <a asp-action="Delete" asp-route-id="@item.ID" class="btn btn-sm btn-danger delete">Delete</a>
                            </td>
                        </tr>

                        counter++;
                    }
                }
                else
                {
                    <tr>
                        <td class="text-center text-muted" colspan="5">No Article</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

ArticleManagementSystem/Views/Article/Show.cshtml
@model Article
@{
    ViewData["Title"] = "Article Details";
}

<h4>@ViewData["Title"]</h4>
<hr />
<div class="row">
    <div class="col-sm-2">
        <b>@Html.DisplayNameFor(model => model.Title)</b>
    </div>
    <div class="col-10">
        @Html.DisplayFor(model => model.Title)
    </div>
</div>
<div class="row">
    <div class="col-sm-2">
        <b>@Html.DisplayNameFor(model => model.Description)</b>
    </div>
    <div class="col-10">
        @Html.DisplayFor(model => model.Description)
    </div>
</div>
<div class="row">
    <div class="col-sm-2">
        <b>@Html.DisplayNameFor(model => model.Date)</b>
    </div>
    <div class="col-10">
        @Html.DisplayFor(model => model.Date)
    </div>
</div>
<div class="row mt-4">
    <div class="col">
        <a asp-action="Edit" asp-route-id="@Model.ID" class="btn btn-primary mb-3">Edit</a>
        <br/>
        <a asp-action="Index">Back to List</a>
    </div>
</div>